name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --only=production
      
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to app directory
          cd /var/www/html/via/ubicador
          
          # Stop the application
          pm2 stop ubicador || true
          
          # Pull latest changes
          git fetch origin main
          git reset --hard origin/main
          
          # Install/update dependencies
          npm ci --only=production
          
          # Update production routes in JavaScript
          sed -i 's|/api/ubicaciones|/via/ubicador/api/ubicaciones|g' public/js/app.js
          sed -i 's|/api/health|/via/ubicador/api/health|g' public/js/app.js
          sed -i 's|/sw.js|/via/ubicador/sw.js|g' public/index.html
          
          # Ensure .env exists with production settings
          cat > .env << 'ENVEOF'
          PORT=3001
          NODE_ENV=production
          MONGO_URI=mongodb://localhost:27017/ubicador
          API_KEY_WRITE=ubi-write-2025-secure-key-789xyz
          API_KEY_READ=ubi-read-2025-secure-key-456abc
          TZ=America/Argentina/Buenos_Aires
          ENVEOF
          
          # Ensure logs directory exists
          mkdir -p logs
          
          # Restart application
          pm2 start ubicador
          
          # Verify deployment
          sleep 5
          curl -f http://localhost:3001/api/health || exit 1
          
          echo "✅ Deployment successful!"
